### ISSUE TITLE
Questionnaire for members to know their skills, interests, opensource persona

### ISSUE THREAD

**Issue by jiakalita** [ortelius-repo-archive/community#2]
To match contributors to the appropriate working groups or to get a better idea on which tasks to assign them as per their interests, create a google form that will be sent to all members, including any new joinee. We can maintain this data for future reference and while planning tasks. 

Form will include details on -
1) their skills match for the project
2) areas of interest for mapping them to appropriate working group
3) mentor assignment
4) based on opensource persona created by @Neetuj , choose which one they identify with

This can also be used by us to gauge community engagement

**Comment by jiakalita** [comment]
I have created the first draft. Pls share your thoughts @Neetuj @TracyRagan @sbtaylor15 @markyjackson-taulia 

@sbtaylor15 @markyjackson-taulia will definitely need your inputs in refining the options for tech stack/tech skills question.

[Ortelius contributor](https://docs.google.com/forms/d/1lFSvxmoY2OHjKVtmagZkFTqEBrmYxWjthryqPe8ncwQ)

**Comment by sbtaylor15** [comment]
@jiakalita requested access to edit so I can add in the stack/tech skills questions.  Great start!

**Comment by jiakalita** [comment]
@sbtaylor15 added

**Comment by jiakalita** [comment]
Form has been updated with user personas and other pending fields. I think this is good to close. We can start sending out these forms in the mail list and for new members, include it in their discord invitation template or welcome email.
